import type { RouteProp } from "@react-navigation/native";

export type RootStackParamList = {
  Webview: { url: string; title?: string };
  Home: any;
  Splash: any;
  Index: any;
  Dashboard: any;
  BookReader: any;
  BookDetail: any;
  BookCreate: any;
  StudentCreate: any;
  CreateProgram: any;
  LevelScreen: any;
  LevelListScreen: any;
  LevelView: any;
  LevelStudent: any;
  LevelNotes: any;
  LevelResult: any;
  LevelProclamation: any;
  GroupCreate: any;
  GroupView: any;
  Profile: any;
  About: any;
  Faq: any;
  Terms: any;
  Purpose: any;
  Subscription: any;
  Bill: any;
  Team: any;
  TeamView: any;
  Login: any;
  Register: any;
  Message: any;
  CreateChat: any;
  ViewChat: any;
  Users: any;
  SchoolProgram: any;
  SettingPeriod: any;
  SettingCalendar: any;
  SettingProclamation: any;
  SettingDeliberation: any;
  SettingProgress: any;
  SettingRight: any;
  SettingFees: any;
  QuizList: any;
  QuizQuestion: any;
  QuizQuestionAnswer: any;
  Challenge: any;
  Expiration: any;
};

export type WebviewScreenRouteProp = RouteProp<RootStackParamList, "Webview">;
export type TeamScreenRouteProp = RouteProp<RootStackParamList, "TeamView">;
export type ProfileScreenRouteProp = RouteProp<RootStackParamList, "Profil">;
export type LevelScreenRouteProp = RouteProp<RootStackParamList, "LevelView">;

export declare type eventType = "info" | "success" | "wrong" | "warning";
